---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pastry-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastry-api
  template:
    metadata:
      labels:
        app: pastry-api
    spec:
      containers:
        - name: pastry-api
          image: mmatur/pastry-api:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: pastry-api
  namespace: default
  labels:
    app: pastry-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: pastry-api
  selector:
    app: pastry-api